openapi: "3.0.3"
info:
  title: API v1
  version: "1.0.0"
  description: Example API specification for WAF OpenAPI validation testing

servers:
  - url: https://api.example.com/v1
    description: Production API

paths:
  /users/{id}:
    get:
      summary: Retrieve user by ID
      description: Returns a single user by their unique ID
      operationId: getUserById
      parameters:
        - name: id
          in: path
          required: true
          description: The unique user identifier
          schema:
            type: integer
            minimum: 1
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: User ID
                  name:
                    type: string
                    description: User's full name
                  email:
                    type: string
                    format: email
                    description: User's email address
        "404":
          description: User not found
        "400":
          description: Invalid ID supplied

  /users:
    post:
      summary: Create new user
      description: Creates a new user account
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - age
              properties:
                name:
                  type: string
                  minLength: 2
                  maxLength: 100
                  description: User's full name
                email:
                  type: string
                  format: email
                  description: User's email address
                age:
                  type: integer
                  minimum: 18
                  maximum: 120
                  description: User's age (must be 18-120)
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: Newly created user ID
        "400":
          description: Invalid input
        "409":
          description: Email already exists
